services:
  postgres:
    image: postgres:18.0
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /data/postgres
    ports:
    - 5432:5432
    volumes:
      - postgres:/data/postgres

  keycloak-db:
    image: postgres:18.0
    container_name: keycloak-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${KEYCLOAK_DB_USERNAME}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      POSTGRES_DB: ${KEYCLOAK_DB_NAME}
      PGDATA: /data/postgres
    volumes:
      - keycloak-postgres:/data/postgres

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.3
    command:
      - start-dev
    ports:
      - "9090:8080"
    depends_on:
      - keycloak-db
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/${KEYCLOAK_DB_NAME}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USERNAME}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}


volumes:
  postgres:
  keycloak-postgres:
  keycloak:
