name: "banki-app"
services:
  banki-backend:
    build:
      context: .
      dockerfile: spring.Dockerfile
    container_name: "banki-backend-app"
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - banki-postgres
      - keycloak
  banki-postgres:
    container_name: "banki-postgres"
    image: postgres:18.0
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /data/postgres
    ports:
    - 5432:5432
    volumes:
      - postgres:/data/postgres

  keycloak-db:
    image: postgres:18.0
    container_name: "banki-keycloak-db"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${KEYCLOAK_DB_USERNAME}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      POSTGRES_DB: ${KEYCLOAK_DB_NAME}
      PGDATA: /data/postgres
    volumes:
      - keycloak-postgres:/data/postgres

  keycloak:
    container_name: "banki-keycloak"
    image: quay.io/keycloak/keycloak:26.3.3
    volumes:
      - ./keycloak-export:/opt/keycloak/data/import
    command:
      - start-dev
      - --import-realm
    depends_on:
      - keycloak-db
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/${KEYCLOAK_DB_NAME}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USERNAME}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}

  nginx:
    image: nginx
    container_name: banki-nginx
    ports:
      - "9090:9090"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - keycloak

volumes:
  postgres:
  keycloak-postgres:
