spring:
  datasource:
    url: ${DB_URL}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
  config:
    import: optional:file:../.env[.properties]

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_FULL_URL}/realms/${VITE_KEYCLOAK_REALM_NAME}/protocol/openid-connect/certs
          issuer-uri: ${KEYCLOAK_FULL_URL}/realms/${VITE_KEYCLOAK_REALM_NAME}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${SMTP_KEY}
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
    from: no-reply@banki.com

server:
  forward-headers-strategy: framework
  servlet:
    context-path: /

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /docs.html

mail:
  from: ${FROM_EMAIL}

keycloak:
  auth-server-url: ${KEYCLOAK_FULL_URL}
  realm: ${VITE_KEYCLOAK_REALM_NAME}
  client-id: ${VITE_KEYCLOAK_CLIENT_ID}
  client-secret: ${VITE_KEYCLOAK_CLIENT_SECRET}

logging:
  level:
    reactor:
      netty:
        http:
          client: DEBUG
    io:
      netty:
        handler:
          ssl: DEBUG
    tp:
      securite:
        banki:
          service:
            KeycloakAdminService: DEBUG